### ISSUE TITLE
can you please rectify the error

### ISSUE THREAD

**Issue by pingaliSravanthi** [kb22/Heart-Disease-Prediction#1]
![error](https://user-images.githubusercontent.com/49191347/68177997-392ba780-ffb0-11e9-8321-bf1221d8e648.JPG)

**Comment by kb22** [comment]
I am not getting this error. Did you run the code blocks out of order? Or not use the dataset included in the repository?

**Comment by pingaliSravanthi** [comment]
I used the same dataset and I executed them in cell wise only.

**Comment by kb22** [comment]
I've confirmed the same again. It's working perfectly fine.
Can you share your system details along with the Python and other package versions?

**Comment by pingaliSravanthi** [comment]
Yup, Thanks for your reply... If I run it in Local Machine it is showing Error if I run it in Online there is no Error.  Error Rectified Thank You and 

How to Give manual Inputs from User and how to predict those manual Inputs for these four algorithms?

**Comment by kb22** [comment]
You can create an application that does that. Refer to my other project https://github.com/kb22/ML-React-App-Template on GitHub and the article https://towardsdatascience.com/create-a-complete-machine-learning-web-application-using-react-and-flask-859340bddb33 which describe how I created a ML app with user inputs.

**Comment by pingaliSravanthi** [comment]
Cant, we implement in the same code https://github.com/kb22/Heart-Disease-Prediction/blob/master/Heart%20Disease%20Prediction.ipynb without using Flask and React?? Just by giving values in Dictionaries or list?

**Comment by kb22** [comment]
Yes, you can do the same without Flask and React.
